# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\rewrite

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\rewrite

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\rewrite\CMakeFiles D:\rewrite\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\rewrite\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SDLStructured

# Build rule for target.
SDLStructured: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 SDLStructured
.PHONY : SDLStructured

# fast build rule for target.
SDLStructured/fast:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/build
.PHONY : SDLStructured/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/main.cpp.s
.PHONY : main.cpp.s

src/AI/AI.o: src/AI/AI.cpp.o

.PHONY : src/AI/AI.o

# target to build an object file
src/AI/AI.cpp.o:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/AI/AI.cpp.o
.PHONY : src/AI/AI.cpp.o

src/AI/AI.i: src/AI/AI.cpp.i

.PHONY : src/AI/AI.i

# target to preprocess a source file
src/AI/AI.cpp.i:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/AI/AI.cpp.i
.PHONY : src/AI/AI.cpp.i

src/AI/AI.s: src/AI/AI.cpp.s

.PHONY : src/AI/AI.s

# target to generate assembly for a file
src/AI/AI.cpp.s:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/AI/AI.cpp.s
.PHONY : src/AI/AI.cpp.s

src/AI/localplayer.o: src/AI/localplayer.cpp.o

.PHONY : src/AI/localplayer.o

# target to build an object file
src/AI/localplayer.cpp.o:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/AI/localplayer.cpp.o
.PHONY : src/AI/localplayer.cpp.o

src/AI/localplayer.i: src/AI/localplayer.cpp.i

.PHONY : src/AI/localplayer.i

# target to preprocess a source file
src/AI/localplayer.cpp.i:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/AI/localplayer.cpp.i
.PHONY : src/AI/localplayer.cpp.i

src/AI/localplayer.s: src/AI/localplayer.cpp.s

.PHONY : src/AI/localplayer.s

# target to generate assembly for a file
src/AI/localplayer.cpp.s:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/AI/localplayer.cpp.s
.PHONY : src/AI/localplayer.cpp.s

src/AI/randomai.o: src/AI/randomai.cpp.o

.PHONY : src/AI/randomai.o

# target to build an object file
src/AI/randomai.cpp.o:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/AI/randomai.cpp.o
.PHONY : src/AI/randomai.cpp.o

src/AI/randomai.i: src/AI/randomai.cpp.i

.PHONY : src/AI/randomai.i

# target to preprocess a source file
src/AI/randomai.cpp.i:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/AI/randomai.cpp.i
.PHONY : src/AI/randomai.cpp.i

src/AI/randomai.s: src/AI/randomai.cpp.s

.PHONY : src/AI/randomai.s

# target to generate assembly for a file
src/AI/randomai.cpp.s:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/AI/randomai.cpp.s
.PHONY : src/AI/randomai.cpp.s

src/Pieces/bishop.o: src/Pieces/bishop.cpp.o

.PHONY : src/Pieces/bishop.o

# target to build an object file
src/Pieces/bishop.cpp.o:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/Pieces/bishop.cpp.o
.PHONY : src/Pieces/bishop.cpp.o

src/Pieces/bishop.i: src/Pieces/bishop.cpp.i

.PHONY : src/Pieces/bishop.i

# target to preprocess a source file
src/Pieces/bishop.cpp.i:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/Pieces/bishop.cpp.i
.PHONY : src/Pieces/bishop.cpp.i

src/Pieces/bishop.s: src/Pieces/bishop.cpp.s

.PHONY : src/Pieces/bishop.s

# target to generate assembly for a file
src/Pieces/bishop.cpp.s:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/Pieces/bishop.cpp.s
.PHONY : src/Pieces/bishop.cpp.s

src/Pieces/king.o: src/Pieces/king.cpp.o

.PHONY : src/Pieces/king.o

# target to build an object file
src/Pieces/king.cpp.o:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/Pieces/king.cpp.o
.PHONY : src/Pieces/king.cpp.o

src/Pieces/king.i: src/Pieces/king.cpp.i

.PHONY : src/Pieces/king.i

# target to preprocess a source file
src/Pieces/king.cpp.i:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/Pieces/king.cpp.i
.PHONY : src/Pieces/king.cpp.i

src/Pieces/king.s: src/Pieces/king.cpp.s

.PHONY : src/Pieces/king.s

# target to generate assembly for a file
src/Pieces/king.cpp.s:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/Pieces/king.cpp.s
.PHONY : src/Pieces/king.cpp.s

src/Pieces/knight.o: src/Pieces/knight.cpp.o

.PHONY : src/Pieces/knight.o

# target to build an object file
src/Pieces/knight.cpp.o:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/Pieces/knight.cpp.o
.PHONY : src/Pieces/knight.cpp.o

src/Pieces/knight.i: src/Pieces/knight.cpp.i

.PHONY : src/Pieces/knight.i

# target to preprocess a source file
src/Pieces/knight.cpp.i:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/Pieces/knight.cpp.i
.PHONY : src/Pieces/knight.cpp.i

src/Pieces/knight.s: src/Pieces/knight.cpp.s

.PHONY : src/Pieces/knight.s

# target to generate assembly for a file
src/Pieces/knight.cpp.s:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/Pieces/knight.cpp.s
.PHONY : src/Pieces/knight.cpp.s

src/Pieces/pawn.o: src/Pieces/pawn.cpp.o

.PHONY : src/Pieces/pawn.o

# target to build an object file
src/Pieces/pawn.cpp.o:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/Pieces/pawn.cpp.o
.PHONY : src/Pieces/pawn.cpp.o

src/Pieces/pawn.i: src/Pieces/pawn.cpp.i

.PHONY : src/Pieces/pawn.i

# target to preprocess a source file
src/Pieces/pawn.cpp.i:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/Pieces/pawn.cpp.i
.PHONY : src/Pieces/pawn.cpp.i

src/Pieces/pawn.s: src/Pieces/pawn.cpp.s

.PHONY : src/Pieces/pawn.s

# target to generate assembly for a file
src/Pieces/pawn.cpp.s:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/Pieces/pawn.cpp.s
.PHONY : src/Pieces/pawn.cpp.s

src/Pieces/queen.o: src/Pieces/queen.cpp.o

.PHONY : src/Pieces/queen.o

# target to build an object file
src/Pieces/queen.cpp.o:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/Pieces/queen.cpp.o
.PHONY : src/Pieces/queen.cpp.o

src/Pieces/queen.i: src/Pieces/queen.cpp.i

.PHONY : src/Pieces/queen.i

# target to preprocess a source file
src/Pieces/queen.cpp.i:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/Pieces/queen.cpp.i
.PHONY : src/Pieces/queen.cpp.i

src/Pieces/queen.s: src/Pieces/queen.cpp.s

.PHONY : src/Pieces/queen.s

# target to generate assembly for a file
src/Pieces/queen.cpp.s:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/Pieces/queen.cpp.s
.PHONY : src/Pieces/queen.cpp.s

src/Pieces/rook.o: src/Pieces/rook.cpp.o

.PHONY : src/Pieces/rook.o

# target to build an object file
src/Pieces/rook.cpp.o:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/Pieces/rook.cpp.o
.PHONY : src/Pieces/rook.cpp.o

src/Pieces/rook.i: src/Pieces/rook.cpp.i

.PHONY : src/Pieces/rook.i

# target to preprocess a source file
src/Pieces/rook.cpp.i:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/Pieces/rook.cpp.i
.PHONY : src/Pieces/rook.cpp.i

src/Pieces/rook.s: src/Pieces/rook.cpp.s

.PHONY : src/Pieces/rook.s

# target to generate assembly for a file
src/Pieces/rook.cpp.s:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/Pieces/rook.cpp.s
.PHONY : src/Pieces/rook.cpp.s

src/UI/button.o: src/UI/button.cpp.o

.PHONY : src/UI/button.o

# target to build an object file
src/UI/button.cpp.o:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/UI/button.cpp.o
.PHONY : src/UI/button.cpp.o

src/UI/button.i: src/UI/button.cpp.i

.PHONY : src/UI/button.i

# target to preprocess a source file
src/UI/button.cpp.i:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/UI/button.cpp.i
.PHONY : src/UI/button.cpp.i

src/UI/button.s: src/UI/button.cpp.s

.PHONY : src/UI/button.s

# target to generate assembly for a file
src/UI/button.cpp.s:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/UI/button.cpp.s
.PHONY : src/UI/button.cpp.s

src/UI/label.o: src/UI/label.cpp.o

.PHONY : src/UI/label.o

# target to build an object file
src/UI/label.cpp.o:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/UI/label.cpp.o
.PHONY : src/UI/label.cpp.o

src/UI/label.i: src/UI/label.cpp.i

.PHONY : src/UI/label.i

# target to preprocess a source file
src/UI/label.cpp.i:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/UI/label.cpp.i
.PHONY : src/UI/label.cpp.i

src/UI/label.s: src/UI/label.cpp.s

.PHONY : src/UI/label.s

# target to generate assembly for a file
src/UI/label.cpp.s:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/UI/label.cpp.s
.PHONY : src/UI/label.cpp.s

src/UI/messagelog.o: src/UI/messagelog.cpp.o

.PHONY : src/UI/messagelog.o

# target to build an object file
src/UI/messagelog.cpp.o:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/UI/messagelog.cpp.o
.PHONY : src/UI/messagelog.cpp.o

src/UI/messagelog.i: src/UI/messagelog.cpp.i

.PHONY : src/UI/messagelog.i

# target to preprocess a source file
src/UI/messagelog.cpp.i:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/UI/messagelog.cpp.i
.PHONY : src/UI/messagelog.cpp.i

src/UI/messagelog.s: src/UI/messagelog.cpp.s

.PHONY : src/UI/messagelog.s

# target to generate assembly for a file
src/UI/messagelog.cpp.s:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/UI/messagelog.cpp.s
.PHONY : src/UI/messagelog.cpp.s

src/UI/text.o: src/UI/text.cpp.o

.PHONY : src/UI/text.o

# target to build an object file
src/UI/text.cpp.o:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/UI/text.cpp.o
.PHONY : src/UI/text.cpp.o

src/UI/text.i: src/UI/text.cpp.i

.PHONY : src/UI/text.i

# target to preprocess a source file
src/UI/text.cpp.i:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/UI/text.cpp.i
.PHONY : src/UI/text.cpp.i

src/UI/text.s: src/UI/text.cpp.s

.PHONY : src/UI/text.s

# target to generate assembly for a file
src/UI/text.cpp.s:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/UI/text.cpp.s
.PHONY : src/UI/text.cpp.s

src/UI/uielement.o: src/UI/uielement.cpp.o

.PHONY : src/UI/uielement.o

# target to build an object file
src/UI/uielement.cpp.o:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/UI/uielement.cpp.o
.PHONY : src/UI/uielement.cpp.o

src/UI/uielement.i: src/UI/uielement.cpp.i

.PHONY : src/UI/uielement.i

# target to preprocess a source file
src/UI/uielement.cpp.i:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/UI/uielement.cpp.i
.PHONY : src/UI/uielement.cpp.i

src/UI/uielement.s: src/UI/uielement.cpp.s

.PHONY : src/UI/uielement.s

# target to generate assembly for a file
src/UI/uielement.cpp.s:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/UI/uielement.cpp.s
.PHONY : src/UI/uielement.cpp.s

src/gamestategame.o: src/gamestategame.cpp.o

.PHONY : src/gamestategame.o

# target to build an object file
src/gamestategame.cpp.o:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/gamestategame.cpp.o
.PHONY : src/gamestategame.cpp.o

src/gamestategame.i: src/gamestategame.cpp.i

.PHONY : src/gamestategame.i

# target to preprocess a source file
src/gamestategame.cpp.i:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/gamestategame.cpp.i
.PHONY : src/gamestategame.cpp.i

src/gamestategame.s: src/gamestategame.cpp.s

.PHONY : src/gamestategame.s

# target to generate assembly for a file
src/gamestategame.cpp.s:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/gamestategame.cpp.s
.PHONY : src/gamestategame.cpp.s

src/gamestatemenu.o: src/gamestatemenu.cpp.o

.PHONY : src/gamestatemenu.o

# target to build an object file
src/gamestatemenu.cpp.o:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/gamestatemenu.cpp.o
.PHONY : src/gamestatemenu.cpp.o

src/gamestatemenu.i: src/gamestatemenu.cpp.i

.PHONY : src/gamestatemenu.i

# target to preprocess a source file
src/gamestatemenu.cpp.i:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/gamestatemenu.cpp.i
.PHONY : src/gamestatemenu.cpp.i

src/gamestatemenu.s: src/gamestatemenu.cpp.s

.PHONY : src/gamestatemenu.s

# target to generate assembly for a file
src/gamestatemenu.cpp.s:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/gamestatemenu.cpp.s
.PHONY : src/gamestatemenu.cpp.s

src/grid.o: src/grid.cpp.o

.PHONY : src/grid.o

# target to build an object file
src/grid.cpp.o:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/grid.cpp.o
.PHONY : src/grid.cpp.o

src/grid.i: src/grid.cpp.i

.PHONY : src/grid.i

# target to preprocess a source file
src/grid.cpp.i:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/grid.cpp.i
.PHONY : src/grid.cpp.i

src/grid.s: src/grid.cpp.s

.PHONY : src/grid.s

# target to generate assembly for a file
src/grid.cpp.s:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/grid.cpp.s
.PHONY : src/grid.cpp.s

src/inputmanager.o: src/inputmanager.cpp.o

.PHONY : src/inputmanager.o

# target to build an object file
src/inputmanager.cpp.o:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/inputmanager.cpp.o
.PHONY : src/inputmanager.cpp.o

src/inputmanager.i: src/inputmanager.cpp.i

.PHONY : src/inputmanager.i

# target to preprocess a source file
src/inputmanager.cpp.i:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/inputmanager.cpp.i
.PHONY : src/inputmanager.cpp.i

src/inputmanager.s: src/inputmanager.cpp.s

.PHONY : src/inputmanager.s

# target to generate assembly for a file
src/inputmanager.cpp.s:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/inputmanager.cpp.s
.PHONY : src/inputmanager.cpp.s

src/log.o: src/log.cpp.o

.PHONY : src/log.o

# target to build an object file
src/log.cpp.o:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/log.cpp.o
.PHONY : src/log.cpp.o

src/log.i: src/log.cpp.i

.PHONY : src/log.i

# target to preprocess a source file
src/log.cpp.i:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/log.cpp.i
.PHONY : src/log.cpp.i

src/log.s: src/log.cpp.s

.PHONY : src/log.s

# target to generate assembly for a file
src/log.cpp.s:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/log.cpp.s
.PHONY : src/log.cpp.s

src/music.o: src/music.cpp.o

.PHONY : src/music.o

# target to build an object file
src/music.cpp.o:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/music.cpp.o
.PHONY : src/music.cpp.o

src/music.i: src/music.cpp.i

.PHONY : src/music.i

# target to preprocess a source file
src/music.cpp.i:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/music.cpp.i
.PHONY : src/music.cpp.i

src/music.s: src/music.cpp.s

.PHONY : src/music.s

# target to generate assembly for a file
src/music.cpp.s:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/music.cpp.s
.PHONY : src/music.cpp.s

src/piece.o: src/piece.cpp.o

.PHONY : src/piece.o

# target to build an object file
src/piece.cpp.o:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/piece.cpp.o
.PHONY : src/piece.cpp.o

src/piece.i: src/piece.cpp.i

.PHONY : src/piece.i

# target to preprocess a source file
src/piece.cpp.i:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/piece.cpp.i
.PHONY : src/piece.cpp.i

src/piece.s: src/piece.cpp.s

.PHONY : src/piece.s

# target to generate assembly for a file
src/piece.cpp.s:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/piece.cpp.s
.PHONY : src/piece.cpp.s

src/player.o: src/player.cpp.o

.PHONY : src/player.o

# target to build an object file
src/player.cpp.o:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/player.cpp.o
.PHONY : src/player.cpp.o

src/player.i: src/player.cpp.i

.PHONY : src/player.i

# target to preprocess a source file
src/player.cpp.i:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/player.cpp.i
.PHONY : src/player.cpp.i

src/player.s: src/player.cpp.s

.PHONY : src/player.s

# target to generate assembly for a file
src/player.cpp.s:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/player.cpp.s
.PHONY : src/player.cpp.s

src/sdl.o: src/sdl.cpp.o

.PHONY : src/sdl.o

# target to build an object file
src/sdl.cpp.o:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/sdl.cpp.o
.PHONY : src/sdl.cpp.o

src/sdl.i: src/sdl.cpp.i

.PHONY : src/sdl.i

# target to preprocess a source file
src/sdl.cpp.i:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/sdl.cpp.i
.PHONY : src/sdl.cpp.i

src/sdl.s: src/sdl.cpp.s

.PHONY : src/sdl.s

# target to generate assembly for a file
src/sdl.cpp.s:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/sdl.cpp.s
.PHONY : src/sdl.cpp.s

src/shapes.o: src/shapes.cpp.o

.PHONY : src/shapes.o

# target to build an object file
src/shapes.cpp.o:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/shapes.cpp.o
.PHONY : src/shapes.cpp.o

src/shapes.i: src/shapes.cpp.i

.PHONY : src/shapes.i

# target to preprocess a source file
src/shapes.cpp.i:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/shapes.cpp.i
.PHONY : src/shapes.cpp.i

src/shapes.s: src/shapes.cpp.s

.PHONY : src/shapes.s

# target to generate assembly for a file
src/shapes.cpp.s:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/shapes.cpp.s
.PHONY : src/shapes.cpp.s

src/soundeffects.o: src/soundeffects.cpp.o

.PHONY : src/soundeffects.o

# target to build an object file
src/soundeffects.cpp.o:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/soundeffects.cpp.o
.PHONY : src/soundeffects.cpp.o

src/soundeffects.i: src/soundeffects.cpp.i

.PHONY : src/soundeffects.i

# target to preprocess a source file
src/soundeffects.cpp.i:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/soundeffects.cpp.i
.PHONY : src/soundeffects.cpp.i

src/soundeffects.s: src/soundeffects.cpp.s

.PHONY : src/soundeffects.s

# target to generate assembly for a file
src/soundeffects.cpp.s:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/soundeffects.cpp.s
.PHONY : src/soundeffects.cpp.s

src/sprite.o: src/sprite.cpp.o

.PHONY : src/sprite.o

# target to build an object file
src/sprite.cpp.o:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/sprite.cpp.o
.PHONY : src/sprite.cpp.o

src/sprite.i: src/sprite.cpp.i

.PHONY : src/sprite.i

# target to preprocess a source file
src/sprite.cpp.i:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/sprite.cpp.i
.PHONY : src/sprite.cpp.i

src/sprite.s: src/sprite.cpp.s

.PHONY : src/sprite.s

# target to generate assembly for a file
src/sprite.cpp.s:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/sprite.cpp.s
.PHONY : src/sprite.cpp.s

src/statemanager.o: src/statemanager.cpp.o

.PHONY : src/statemanager.o

# target to build an object file
src/statemanager.cpp.o:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/statemanager.cpp.o
.PHONY : src/statemanager.cpp.o

src/statemanager.i: src/statemanager.cpp.i

.PHONY : src/statemanager.i

# target to preprocess a source file
src/statemanager.cpp.i:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/statemanager.cpp.i
.PHONY : src/statemanager.cpp.i

src/statemanager.s: src/statemanager.cpp.s

.PHONY : src/statemanager.s

# target to generate assembly for a file
src/statemanager.cpp.s:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/statemanager.cpp.s
.PHONY : src/statemanager.cpp.s

src/tile.o: src/tile.cpp.o

.PHONY : src/tile.o

# target to build an object file
src/tile.cpp.o:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/tile.cpp.o
.PHONY : src/tile.cpp.o

src/tile.i: src/tile.cpp.i

.PHONY : src/tile.i

# target to preprocess a source file
src/tile.cpp.i:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/tile.cpp.i
.PHONY : src/tile.cpp.i

src/tile.s: src/tile.cpp.s

.PHONY : src/tile.s

# target to generate assembly for a file
src/tile.cpp.s:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/tile.cpp.s
.PHONY : src/tile.cpp.s

src/timer.o: src/timer.cpp.o

.PHONY : src/timer.o

# target to build an object file
src/timer.cpp.o:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/timer.cpp.o
.PHONY : src/timer.cpp.o

src/timer.i: src/timer.cpp.i

.PHONY : src/timer.i

# target to preprocess a source file
src/timer.cpp.i:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/timer.cpp.i
.PHONY : src/timer.cpp.i

src/timer.s: src/timer.cpp.s

.PHONY : src/timer.s

# target to generate assembly for a file
src/timer.cpp.s:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/timer.cpp.s
.PHONY : src/timer.cpp.s

src/window.o: src/window.cpp.o

.PHONY : src/window.o

# target to build an object file
src/window.cpp.o:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/window.cpp.o
.PHONY : src/window.cpp.o

src/window.i: src/window.cpp.i

.PHONY : src/window.i

# target to preprocess a source file
src/window.cpp.i:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/window.cpp.i
.PHONY : src/window.cpp.i

src/window.s: src/window.cpp.s

.PHONY : src/window.s

# target to generate assembly for a file
src/window.cpp.s:
	$(MAKE) -f CMakeFiles\SDLStructured.dir\build.make CMakeFiles/SDLStructured.dir/src/window.cpp.s
.PHONY : src/window.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... rebuild_cache
	@echo ... SDLStructured
	@echo ... edit_cache
	@echo ... main.o
	@echo ... main.i
	@echo ... main.s
	@echo ... src/AI/AI.o
	@echo ... src/AI/AI.i
	@echo ... src/AI/AI.s
	@echo ... src/AI/localplayer.o
	@echo ... src/AI/localplayer.i
	@echo ... src/AI/localplayer.s
	@echo ... src/AI/randomai.o
	@echo ... src/AI/randomai.i
	@echo ... src/AI/randomai.s
	@echo ... src/Pieces/bishop.o
	@echo ... src/Pieces/bishop.i
	@echo ... src/Pieces/bishop.s
	@echo ... src/Pieces/king.o
	@echo ... src/Pieces/king.i
	@echo ... src/Pieces/king.s
	@echo ... src/Pieces/knight.o
	@echo ... src/Pieces/knight.i
	@echo ... src/Pieces/knight.s
	@echo ... src/Pieces/pawn.o
	@echo ... src/Pieces/pawn.i
	@echo ... src/Pieces/pawn.s
	@echo ... src/Pieces/queen.o
	@echo ... src/Pieces/queen.i
	@echo ... src/Pieces/queen.s
	@echo ... src/Pieces/rook.o
	@echo ... src/Pieces/rook.i
	@echo ... src/Pieces/rook.s
	@echo ... src/UI/button.o
	@echo ... src/UI/button.i
	@echo ... src/UI/button.s
	@echo ... src/UI/label.o
	@echo ... src/UI/label.i
	@echo ... src/UI/label.s
	@echo ... src/UI/messagelog.o
	@echo ... src/UI/messagelog.i
	@echo ... src/UI/messagelog.s
	@echo ... src/UI/text.o
	@echo ... src/UI/text.i
	@echo ... src/UI/text.s
	@echo ... src/UI/uielement.o
	@echo ... src/UI/uielement.i
	@echo ... src/UI/uielement.s
	@echo ... src/gamestategame.o
	@echo ... src/gamestategame.i
	@echo ... src/gamestategame.s
	@echo ... src/gamestatemenu.o
	@echo ... src/gamestatemenu.i
	@echo ... src/gamestatemenu.s
	@echo ... src/grid.o
	@echo ... src/grid.i
	@echo ... src/grid.s
	@echo ... src/inputmanager.o
	@echo ... src/inputmanager.i
	@echo ... src/inputmanager.s
	@echo ... src/log.o
	@echo ... src/log.i
	@echo ... src/log.s
	@echo ... src/music.o
	@echo ... src/music.i
	@echo ... src/music.s
	@echo ... src/piece.o
	@echo ... src/piece.i
	@echo ... src/piece.s
	@echo ... src/player.o
	@echo ... src/player.i
	@echo ... src/player.s
	@echo ... src/sdl.o
	@echo ... src/sdl.i
	@echo ... src/sdl.s
	@echo ... src/shapes.o
	@echo ... src/shapes.i
	@echo ... src/shapes.s
	@echo ... src/soundeffects.o
	@echo ... src/soundeffects.i
	@echo ... src/soundeffects.s
	@echo ... src/sprite.o
	@echo ... src/sprite.i
	@echo ... src/sprite.s
	@echo ... src/statemanager.o
	@echo ... src/statemanager.i
	@echo ... src/statemanager.s
	@echo ... src/tile.o
	@echo ... src/tile.i
	@echo ... src/tile.s
	@echo ... src/timer.o
	@echo ... src/timer.i
	@echo ... src/timer.s
	@echo ... src/window.o
	@echo ... src/window.i
	@echo ... src/window.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

